### ISSUE TITLE
Root file index questions

### ISSUE THREAD

**Issue by thomas-neuburger** [turulix/obsidian-folder-index#21]
Experimenting with this plugin. Nice idea.

Questions: 
- What does the setting "Root file index" do? 
- Does it matter which file is chosen?
- Mine seems to have defaulted to Dashboard.md without my having chosen it. Why?

Finally:
- The created index file appearing in file browser list is confusing. Will the "hide" option be implemented soon? If not, is there a way to use Style Settings or Supercharged Links to color it differently?

Thanks,

Thomas

**Comment by turulix** [comment]
The Root file index, is the file which is selected, when you click on the name of the Vault. This seems to be broken currently because of a new Version of Obsidian. Need to investigate once I have time.

I sadly currently don't have time to keep developing this plugin. Feel free to open a pull request to implement  it :)

**Comment by thomas-neuburger** [comment]
Thanks for the fast reply.

Thomas
